#!/bin/bash

# Admin Account Setup Script
# This script provides the commands to set up admin access

echo "========================================="
echo "  Golden Crown Dental - Admin Setup"
echo "========================================="
echo ""
echo "Admin Login Credentials:"
echo "  Email: admin@goldencrown.com"
echo "  Password: GoldenCrown2026!"
echo ""
echo "========================================="
echo ""
echo "Option 1: Create via Web Interface (RECOMMENDED)"
echo ""
echo "1. Go to: https://dentist-platform-six.vercel.app/auth"
echo "2. Sign up with the above credentials"
echo "3. Then run this command to make the user admin:"
echo ""
echo "   Open Firebase Console and manually add role field"
echo "   OR use the script below after signup"
echo ""
echo "========================================="
echo ""
echo "Option 2: Manual Firebase Console Setup"
echo ""
echo "1. Open: https://console.firebase.google.com/project/dentist-demo-2026/authentication"
echo "2. Click 'Add user'"
echo "3. Email: admin@goldencrown.com"
echo "4. Password: GoldenCrown2026!"
echo "5. Copy the User UID"
echo "6. Go to Firestore: https://console.firebase.google.com/project/dentist-demo-2026/firestore"
echo "7. Create collection 'users'"
echo "8. Document ID: [paste the UID]"
echo "9. Add fields:"
echo "   - email: admin@goldencrown.com"
echo "   - role: admin"
echo "   - displayName: Golden Crown Admin"
echo ""
echo "========================================="
echo ""
echo "After setup, login at:"
echo "https://dentist-platform-six.vercel.app/admin/login"
echo ""
